=== SotirisDimitrakoulakos/XML_XSD_XSLT_DTD_CSS_Project/1_1.dtd
<?xml version="1.0" encoding="UTF-16"?>
<!ELEMENT customerList (company | person)*>
<!ELEMENT company (company_info, package_offer+)>
<!ELEMENT person (person_info, package_offer+)>
<!ELEMENT person_info (first_name, middle_name?, last_name, person_AFM, person_DOY, person_address)>
<!ELEMENT company_info (name, company_AFM, company_DOY, company_address)>
<!ELEMENT package_offer (giving+, tel_numb*, startPrice, (finalPrice | in_discount), contract_start_date, contract_end_date)>
<!ELEMENT in_discount ((discount_rate, amount_after_disccount) | (amount_after_disccount, discount_rate))>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT person_AFM (#PCDATA)>
<!ELEMENT person_DOY (#PCDATA)>
<!ELEMENT person_address (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT company_AFM (#PCDATA)>
<!ELEMENT company_DOY (#PCDATA)>
<!ELEMENT company_address (#PCDATA)>
<!ELEMENT giving (#PCDATA)>
<!ELEMENT tel_numb (#PCDATA)>
<!ELEMENT startPrice (#PCDATA)>
<!ELEMENT finalPrice (#PCDATA)>
<!ELEMENT contract_start_date (#PCDATA)>
<!ELEMENT contract_end_date (#PCDATA)>
<!ELEMENT discount_rate (#PCDATA)>
<!ELEMENT amount_after_disccount (#PCDATA)>
<!ATTLIST company CompCodeNo ID #REQUIRED>
<!ATTLIST person PersonCodeNo ID #REQUIRED>
<!ATTLIST package_offer package_category (B_START|B_LITE|P_LITE|P_START|B_all|P_all|B_smart|P_smart) #REQUIRED contract_No ID #REQUIRED>
<!ATTLIST startPrice unitS CDATA #FIXED "euro" forperiodS CDATA #FIXED "month">
<!ATTLIST finalPrice unitF CDATA #FIXED "euro" forperiodF CDATA #FIXED "month">
<!ATTLIST amount_after_discount unit CDATA #FIXED "euro" forperiod CDATA #FIXED "month">

=== SotirisDimitrakoulakos/XML_XSD_XSLT_DTD_CSS_Project/1_3.xml
<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE customerList SYSTEM "1_1.dtd">
<customerList>
  <company CompCodeNo="CA1">
    <package_offer package_category="P_START" contract_No="C1">
      <giving>Insurance</giving>
      <tel_numb>210-1234567</tel_numb>
      <startPrice unitS="euro">10</startPrice>
      <finalPrice forperiodF="month">100</finalPrice>
      <contract_start_date>29-05-2023</contract_start_date>
      <contract_end_date>29-06-2023</contract_end_date>
    </package_offer>
    <package_offer package_category="P_all" contract_No="C2">
      <giving>Bonus Tools</giving>
      <tel_numb>210-7654321</tel_numb>
      <startPrice unitS="euro" forperiodS="month">20</startPrice>
      <finalPrice unitF="euro" forperiodF="month">200</finalPrice>
      <contract_start_date>30-05-2023</contract_start_date>
      <contract_end_date>30-06-2023</contract_end_date>
    </package_offer>
  </company>
  <person PersonCodeNo="PA1">
    <person_info>
      <first_name>Joe</first_name>
      <last_name>Shmo</last_name>
      <person_AFM>3333333333</person_AFM>
      <person_DOY>4444444444</person_DOY>
      <person_address>Street2, 456, Korydallos</person_address>
    </person_info>
  </person>
  <person PersonCodeNo="PA2">
    <person_info>
      <first_name>Sotirios</first_name>
	  <middle_name>A</middle_name>
	  <middle_name>M</middle_name>
      <last_name>Dimitrakoulakos</last_name>
      <person_AFM>5555555555</person_AFM>
      <person_address>Street3, 91, Korydallos</person_address>
    </person_info>
    <package_offer package_category="B_LITE" contract_No="C4">
      <startPrice unitS="euro" forperiodS="month">40</startPrice>
      <in_discount>
	    <discount_rate>0.4</discount_rate>
        <amount_after_disccount>400</amount_after_disccount>
      </in_discount>
      <contract_start_date>02-06-2023</contract_start_date>
      <contract_end_date>02-07-2023</contract_end_date>
    </package_offer>
	<package_offer package_category="B_START" contract_No="C5">
      <giving>Insurance</giving>
      <giving>Bonus Tools</giving>
	  <giving>Free Health Insurance</giving>
      <startPrice unitS="euro" forperiodS="month">50</startPrice>
      <in_discount>False Input</in_discount>
      <contract_start_date>02-06-2023</contract_start_date>
      <contract_end_date>02-07-2023</contract_end_date>
    </package_offer>
	<package_offer package_category="P_LITE" contract_No="C6">
      <giving>Chance for a Free Car</giving>
      <giving>Bonus Rights</giving>
	  <tel_numb>213-7654321</tel_numb>
      <startPrice unitS="dollar" forperiodS="month">60</startPrice>
	  <finalPrice unitF="euro" forperiodF="month">200</finalPrice>
      <in_discount>
        <amount_after_disccount>600</amount_after_disccount>
        <discount_rate>0.6</discount_rate>
      </in_discount>
      <contract_start_date>03-06-2023</contract_start_date>
      <contract_end_date>03-07-2023</contract_end_date>
    </package_offer>
  </person>
</customerList>
