=== SotirisDimitrakoulakos/XML_XSD_XSLT_DTD_CSS_Project/HOME23.dtd
<?xml version="1.0" encoding="UTF-16"?>

<!ELEMENT Epipla_Diakosmisi_AE (name, stores_list, product_categories, room_classification, special_classification, contact_details, store_hours, Services?, product_list)>
<!ELEMENT stores_list (store+)>
<!ELEMENT product_categories (product_type+)>
<!ELEMENT room_classification (room_classes)>
<!ELEMENT room_classes (room_class+)>
<!ELEMENT special_classification (special_classes)>
<!ELEMENT contact_details (Headquarters, stores)>
<!ELEMENT Headquarters (address, ((tel*, email*) | (email*, tel*)))>
<!ELEMENT product_type (#PCDATA)>
<!ELEMENT special_classes ((campaign, outlet) | (outlet, campaign))>
<!ELEMENT stores (shop_store+)>
<!ELEMENT shop_store (address, ((tel*, email*) | (email*, tel*)))>
<!ELEMENT store_hours (Day+)>
<!ELEMENT Day (#PCDATA | Timing)*>
<!ELEMENT Services (shipping_Charges, Assembly_Charges, Interior_Design_Charges?)>
<!ELEMENT shipping_Charges ((charges_Ath_Th, charges_other_places) | (charges_other_places, charges_Ath_Th))>
<!ELEMENT charges_Ath_Th (shipValue+)>
<!ELEMENT charges_other_places (shipValue+)>
<!ELEMENT Assembly_Charges (assValue*)>
<!ELEMENT Interior_Design_Charges (DesValue*)>
<!ELEMENT product_list (product*)>
<!ELEMENT product (product_name, product_code, store_availability, product_descr, product_characteristics, start_value, Final_value)>
<!ELEMENT store_availability (quantity*)>
<!ELEMENT product_characteristics (manufacturer_country?, weight, material*, included*, not_included*, color*, (size | Dimensions*), certified?)>
<!ELEMENT color (#PCDATA | also_available_color)*>
<!ELEMENT Dimensions (height?, length?, width, depth*)>
<!ELEMENT Final_value (#PCDATA | accept_doses)*>
<!ELEMENT accept_doses (num_doses, ammount_dose, With_credit_card?, Interest_free?)>
<!ELEMENT With_credit_card EMPTY>
<!ELEMENT Interest_free EMPTY>
<!ELEMENT num_doses (#PCDATA)>
<!ELEMENT ammount_dose (#PCDATA)>
<!ELEMENT start_value (#PCDATA | offer_rate)*>
<!ELEMENT offer_rate (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT Timing (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT also_available_color (#PCDATA)>
<!ELEMENT certified EMPTY>
<!ELEMENT manufacturer_country (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT material (#PCDATA)>
<!ELEMENT included (#PCDATA)>
<!ELEMENT not_included (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT product_descr (#PCDATA)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT product_code (#PCDATA)>
<!ELEMENT DesValue (#PCDATA)>
<!ELEMENT assValue (#PCDATA)>
<!ELEMENT shipValue (#PCDATA)>
<!ELEMENT room_class (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT store EMPTY>
<!ELEMENT campaign EMPTY>
<!ELEMENT outlet EMPTY>
<!ELEMENT address ANY>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST Epipla_Diakosmisi_AE number_of_products CDATA #REQUIRED Year_opened CDATA #REQUIRED>
<!ATTLIST store strid ID #REQUIRED name CDATA #REQUIRED>
<!ATTLIST product_type prod_class_id ID #REQUIRED>
<!ATTLIST room_class class_id ID #REQUIRED>
<!ATTLIST campaign spclass_id ID #REQUIRED>
<!ATTLIST outlet spclass_id ID #REQUIRED>
<!ATTLIST room_classification value CDATA #FIXED "ανάλογα με την τοποθέτησή τους σε χώρο του σπιτιού">
<!ATTLIST Day day_id ID #REQUIRED>
<!ATTLIST charges_Ath_Th shipping_until CDATA #REQUIRED>
<!ATTLIST charges_other_places shipping_until CDATA #REQUIRED>
<!ATTLIST shipValue ship_weight_category CDATA #REQUIRED shpunit (euro) #IMPLIED>
<!ATTLIST assValue assunit (euro) #IMPLIED ass_category CDATA #REQUIRED>
<!ATTLIST DesValue dessunit (euro) #IMPLIED Des_category CDATA #REQUIRED>
<!ATTLIST Interior_Design_Charges forevery CDATA "room">
<!ATTLIST product product_id ID #REQUIRED prod_class_id IDREFS #REQUIRED>
<!ATTLIST quantity store_id IDREF #REQUIRED>
<!ATTLIST weight unit_weight (kg|gr) #REQUIRED unit_weight_default (kg|gr) "kg">
<!ATTLIST material mtr CDATA #IMPLIED>
<!ATTLIST not_included no_incl CDATA #REQUIRED>
<!ATTLIST included quantity CDATA #IMPLIED>
<!ATTLIST certified certificate CDATA #REQUIRED>
<!ATTLIST color in CDATA #IMPLIED> 
<!ATTLIST also_available_color also_color CDATA #REQUIRED>
<!ATTLIST height unit_height (cm | m) "cm"> 
<!ATTLIST length unit_length (cm | m) "cm"> 
<!ATTLIST width unit_width (cm | m) "cm"> 
<!ATTLIST depth unit_depth CDATA #FIXED "cm" for CDATA #IMPLIED> 
<!ATTLIST start_value valunit CDATA #IMPLIED can_return (yes | no) #IMPLIED can_reserved (yes | no) #IMPLIED option_of_assembly (yes | no) #IMPLIED is_assembled (yes | no) #IMPLIED>
<!ATTLIST Final_value fnlunit CDATA #IMPLIED fnlunit_default CDATA "euro">

=== SotirisDimitrakoulakos/XML_XSD_XSLT_DTD_CSS_Project/HOME23.xml
<?xml version="1.0" encoding="UTF-16"?>
<!DOCTYPE Epipla_Diakosmisi_AE SYSTEM "HOME23.dtd">

<Epipla_Diakosmisi_AE number_of_products="over of 2000" Year_opened="2004">
  <name>ΗΟΜΕ23</name>
  <stores_list>
    <store strid="_1" name="HOME 23 - Αθήνα (Κολωνάκι)" />
    <store strid="_2" name="HOME 23 - Αθήνα (Αεροδρόμιο)" />
    <store strid="_3" name="HOME 23 - Θεσσαλονίκη" />
    <store strid="_4" name="HOME 23 - Ιωάννινα" />
    <store strid="_5" name="HOME 23 - Λάρισσα" />
    <store strid="_6" name="HOME 23 - Ξάνθη" />
    <store strid="_7" name="HOME 23 - Κέρκυρα" />
    <store strid="_8" name="HOME 23 - Καλαμάτα" />
    <store strid="_9" name="HOME 23 - Κρήτη" />
  </stores_list>
  <product_categories>
    <product_type prod_class_id="K1">Καναπέδες και πολυθρόνες</product_type>
    <product_type prod_class_id="K2">Έπιπλα οργάνωσης κι αποθήκευσης</product_type>
    <product_type prod_class_id="K3">Κουζίνα και Πάγκοι Κουζίνας</product_type>
    <product_type prod_class_id="K4">Είδη Σερβιρίσματος</product_type>
    <product_type prod_class_id="K5">Χαλιά</product_type>
    <product_type prod_class_id="K6">Κρεβάτια και Στρώματα και μαξιλάρια</product_type>
    <product_type prod_class_id="K7">Ντουλάπες</product_type>
    <product_type prod_class_id="K8">Βρεφικά -Παιδικά Είδη και έπιπλα</product_type>
    <product_type prod_class_id="K9">Λευκά είδη</product_type>
    <product_type prod_class_id="K10">Φωτισμός</product_type>
    <product_type prod_class_id="K11">Γραφεία</product_type>
    <product_type prod_class_id="K12">Συρταριέρες</product_type>
    <product_type prod_class_id="K13">Τραπέζια</product_type>
    <product_type prod_class_id="K14">Είδη Κουζίνας</product_type>
    <product_type prod_class_id="K15">Σκαμπό και πάγκοι κουζίνας</product_type>
    <product_type prod_class_id="K16">Κομοδίνα</product_type>
    <product_type prod_class_id="K17">Καρέκλες</product_type>
    <product_type prod_class_id="K18">Διακόσμηση Τοίχου και καθρέφτες</product_type>
    <product_type prod_class_id="K19">Διακοσμητικά, κεριά και φυτά</product_type>
    <product_type prod_class_id="K20">Κήπος και εξωτερικοί χώροι</product_type>
    <product_type prod_class_id="K21">Είδη μπάνιου</product_type>
    <product_type prod_class_id="K22">Μπουφέδες</product_type>
    <product_type prod_class_id="K23">Εργαλεία και εξαρτήματα</product_type>
    <product_type prod_class_id="K24">Χόμπι και ασφάλεια</product_type>
    <product_type prod_class_id="K25">Κουρτίνες</product_type>
	<product_type prod_class_id="K26">Ριχτάρια</product_type>
  </product_categories>
  <room_classification value="ανάλογα με την τοποθέτησή τους σε χώρο του σπιτιού">
	<room_classes>
		<room_class class_id="id1">Υπνοδωμάτιο (bedroom)</room_class>
		<room_class class_id="id2">Μπάνιο (bathroom)</room_class>
		<room_class class_id="id3">Δωμάτιο Γραφείου (office)</room_class>
		<room_class class_id="id4">Καθιστικό/Σαλόνι (living_room)</room_class>
		<room_class class_id="id5">Τραπεζαρία (dining_room)</room_class>
		<room_class class_id="id6">Κουζίνα (kitchen)</room_class>
		<room_class class_id="id7">Παιδικό δωμάτιο (kids_room)</room_class>
		<room_class class_id="id8">Εξωτερικοί Χώροι/Κήπος (outdoor)</room_class>
		<room_class class_id="id9">Χώρος Αποθήκευσης (Αποθήκη)/Γκαράζ (storage_room)</room_class>
	</room_classes>
  </room_classification>
  <special_classification>
    <special_classes>
      <campaign spclass_id="_1_"/>
      <outlet spclass_id="_2_"/>
    </special_classes>
  </special_classification>
  <contact_details>
    <Headquarters>
      <address>Παπαρηγοπούλου 345, Αθήνα, ΕΛΛΑΔΑ, 100-45</address>
      <tel>+30 210 12345678</tel>
      <email>xyz@outl.ΗΟΜΕ23.com</email>
    </Headquarters>
    <stores>
      <shop_store>
        <address>xyzw 99, Αθήνα, ΕΛΛΑΔΑ, 100-54</address>
        <tel>+30 210 213359778</tel>
        <email>kolonaki@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Ελ. Βενιζέλου 7, Παιανία, ΕΛΛΑΔΑ, 102-33</address>
        <tel>+30 210 133669785</tel>
        <email>airport@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Τσιμισκί 200, Θεσσαλονίκη, ΕΛΛΑΔΑ, 456-32</address>
        <tel>+30 2310 999669321</tel>
        <email>Thessaloniki@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Σουλίου 67, Ιωάννινα, ΕΛΛΑΔΑ, 323-11</address>
        <tel>+30 26510-432990321</tel>
        <email>Ioannina@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Ασκληπιού 119, Λάρισα, ΕΛΛΑΔΑ, 412-22</address>
        <tel>+30 2410 241111</tel>
        <email>larissa@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>28ης Οκτωβρίου 98, Ξάνθη, ΕΛΛΑΔΑ, 761-33</address>
        <tel>+30 25410 25001</tel>
        <email>xanthi@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Φιλελλήνων 10, Κέρκυρα, ΕΛΛΑΔΑ, 491-31</address>
        <tel>+30 26610 301158</tel>
        <email>kerkira@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Αριστομένους 115, Καλαμάτα, ΕΛΛΑΔΑ, 241-00</address>
        <tel>+30 27210-97967</tel>
        <email>kalamata@outl.ΗΟΜΕ23.com</email>
      </shop_store>
      <shop_store>
        <address>Λεωφ. Κνωσού 13, Ηράκλειο, ΕΛΛΑΔΑ, 714-10</address>
        <tel>+30 2810-211111</tel>
        <email>creta@outl.ΗΟΜΕ23.com</email>
      </shop_store>
    </stores>
  </contact_details>
  <store_hours>
    <Day day_id="id_1">
      Δευτέρα
      <Timing>9:00 am – 15:00 pm</Timing>
    </Day>
    <Day day_id="id_2">
      Τρίτη
      <Timing>9:00 am – 15:00 pm</Timing>
      <Timing>17:00 pm – 21:00 pm</Timing>
    </Day>
    <Day day_id="id_3">
      Τετάρτη
      <Timing>9:00 am – 15:00 pm</Timing>
    </Day>
    <Day day_id="id_4">
      Πέμπτη
      <Timing>9:00 am – 15:00 pm</Timing>
      <Timing>17:00 pm – 21:00 pm</Timing>
    </Day>
    <Day day_id="id_5">
      Παρασκευή
      <Timing>9:00 am –21:00 pm</Timing>
    </Day>
    <Day day_id="id_6">
      Σάββατο
      <Timing>9:00 am –18:00 pm</Timing>
    </Day>
    <Day day_id="id_7">
      Κυριακή
    </Day>
  </store_hours>
  <Services>
    <shipping_Charges>
      <charges_Ath_Th shipping_until="4 εργάσιμων ημερών">
        <shipValue ship_weight_category="για 0 - 15 κιλά" shpunit="euro">4.50</shipValue>
        <shipValue ship_weight_category="για 15.01 - 35 κιλά" shpunit="euro">9.00</shipValue>
        <shipValue ship_weight_category="για 35.01 - 65 κιλά" shpunit="euro">19.00</shipValue>
        <shipValue ship_weight_category="για 65.01 - 100 κιλά" shpunit="euro">29.00</shipValue>
        <shipValue ship_weight_category="για 100.01 - 200 κιλά" shpunit="euro">49.00</shipValue>
        <shipValue ship_weight_category="για 200.01 - 400 κιλά" shpunit="euro">59.00</shipValue>
        <shipValue ship_weight_category="για > 400.01 κιλά" shpunit="euro">69.00</shipValue>
      </charges_Ath_Th>
      <charges_other_places shipping_until="8 εργάσιμων ημερών">
        <shipValue ship_weight_category="για 0 - 15 κιλά" shpunit="euro">7.50</shipValue>
        <shipValue ship_weight_category="για 15.01 - 35 κιλά" shpunit="euro">11.50</shipValue>
        <shipValue ship_weight_category="για 35.01 - 65 κιλά" shpunit="euro">33.00</shipValue>
        <shipValue ship_weight_category="για 65.01 - 100 κιλά" shpunit="euro">58.00</shipValue>
        <shipValue ship_weight_category="για 100.01 - 200 κιλά" shpunit="euro">78.00</shipValue>
        <shipValue ship_weight_category="για 200.01 - 400 κιλά" shpunit="euro">95.00</shipValue>
        <shipValue ship_weight_category="για > 400.01 κιλά" shpunit="euro">105.00</shipValue>
      </charges_other_places>
    </shipping_Charges>
    <Assembly_Charges>
      <assValue assunit="euro" ass_category="για προϊόντα αξίας από  0.01 - 2.500 ευρώ">10% της αξίας του προϊόντος που θέλετε να συναρμολογήσετε</assValue>
      <assValue ass_category="για προϊόντα αξίας >2.500 Ευρώ">δωρεάν</assValue>
    </Assembly_Charges>
    <Interior_Design_Charges>
      <DesValue dessunit="euro" Des_category="&lt; 50m2">200</DesValue>
      <DesValue dessunit="euro" Des_category="&gt; =50m2">350</DesValue>
    </Interior_Design_Charges>
  </Services>
  <product_list>
    <product product_id="No.1" prod_class_id="K21 K9 id2 _2_">
      <product_name>Μπουρνούζι LERUM</product_name>
      <product_code>H28K4741L</product_code>
      <store_availability>
        <quantity store_id="_3">10</quantity>
        <quantity store_id="_2">2</quantity>
      </store_availability>
      <product_descr>Πολύ απαλό και απορροφητικό μπουρνούζι, υφασμένο από 100% βαμβάκι και σε μοναδικές αποχρώσεις που ταιριάζουν και κολακεύουν τον καθένα. Μοναδικής ποιότητας μπουρνούζι με κουκούλα, διαθέσιμο σε 10 αποχρώσεις.</product_descr>
      <product_characteristics>
        <manufacturer_country>Ελλάδα</manufacturer_country>
        <weight unit_weight="gr">480</weight>
        <material mtr="1">100% Βαμβάκι</material>
        <color>Γκρι</color>
        <size>L/XL</size>
		<certified certificate="STANDARD 100 by OEKO-TEX®"/>
      </product_characteristics>
	  <start_value valunit="euro" can_return="no">
		19.99
		<offer_rate>33%</offer_rate>
	  </start_value>
	  <Final_value fnlunit="euro">
		13.50
	  </Final_value>
    </product>
    <product product_id="No.2" prod_class_id="K11 id3">
      <product_name>Γραφείο DERUP 40x100 λευκό</product_name>
      <product_code>K33J4755J</product_code>
      <store_availability>
        <quantity store_id="_3">3</quantity>
        <quantity store_id="_1">2</quantity>
        <quantity store_id="_4">1</quantity>
        <quantity store_id="_5">3</quantity>
        <quantity store_id="_8">2</quantity>
        <quantity store_id="_9">2</quantity>
